services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - ollama-net
    environment:
      - OLLAMA_HOST:0.0.0.0

networks:
  ollama-net:
    driver: bridge

volumes:
  ollama-data: